### ISSUE TITLE
Build windows server with microsoft SQL 

### ISSUE THREAD

**Issue by ZachariahPepper** [Studio-Ops-Org/Studio-2022-S2-Repo#22]
Rob wants a windows server built with microsoft SQL installed

**Comment by westcl4** [comment]
This VM only needs the relevant software installed on it. The software in question is outlined in the reports folder on Teams.

**Comment by westcl4** [comment]
VM has been instatntiated with equivalent hardware. It now needs to have the separate drives associated with it set up to do the SQL server functions. 

Note to future readers: Ensure your resources are on the same address space/vnet as the gateway server, if you want to have the gateway server as protection for your resources!

**Comment by westcl4** [comment]
Hardware has been instantiated. Software setup was tracked in issue #35
